/* JaviEats v2.9 · Baterías de Minijuegos
   Dibuja: 225 conceptos visuales con pistas revisadas para orientar sin regalar la respuesta.
   No lo digas: 225 cartas con 2-4 palabras prohibidas y dificultad interna.
   La dificultad es interna: se usa para equilibrar partidas y no se muestra al jugador. */

window.JAVIEATS_DRAW_SECTIONS = [
  {
    id: "futbol", emoji: "⚽", title: "Fútbol", subtitle: "Territorio Javi · situaciones y objetos del campo",
    cards: [
      { word: "Balón de fútbol", hint: "Está en el centro de casi todo.", difficulty: 1 },
      { word: "Portería", hint: "Está en uno de los extremos.", difficulty: 1 },
      { word: "Penalti", hint: "Puede decidir un partido.", difficulty: 2 },
      { word: "Árbitro", hint: "No juega para ningún equipo.", difficulty: 1 },
      { word: "Tarjeta roja", hint: "Puede cambiar el partido de golpe.", difficulty: 1 },
      { word: "Tarjeta amarilla", hint: "Es una advertencia durante el juego.", difficulty: 1 },
      { word: "Copa del Mundo", hint: "Se consigue muy pocas veces.", difficulty: 2 },
      { word: "Trofeo de fútbol", hint: "Aparece al final de una competición.", difficulty: 1 },
      { word: "Estadio", hint: "Aquí ocurre todo el espectáculo.", difficulty: 1 },
      { word: "Banquillo", hint: "Está junto al terreno de juego.", difficulty: 2 },
      { word: "Portero", hint: "Tiene una función distinta al resto.", difficulty: 1 },
      { word: "Chilena", hint: "Es una acción muy espectacular.", difficulty: 3 },
      { word: "Córner", hint: "Ocurre cerca de una esquina.", difficulty: 2 },
      { word: "Falta", hint: "Puede detener una jugada.", difficulty: 2 },
      { word: "Saque de banda", hint: "Reanuda el juego desde fuera.", difficulty: 2 },
      { word: "Botas de fútbol", hint: "Forma parte de la equipación.", difficulty: 1 },
      { word: "Guantes de portero", hint: "Equipamiento de una posición concreta.", difficulty: 1 },
      { word: "Marcador", hint: "Te dice cómo va el partido.", difficulty: 1 },
      { word: "Entrenamiento de fútbol", hint: "Sucede antes de competir.", difficulty: 2 },
      { word: "Afición", hint: "Se hace notar desde fuera.", difficulty: 2 },
      { word: "Brazalete de capitán", hint: "Lo lleva una sola persona.", difficulty: 2 },
      { word: "Barrera en una falta", hint: "Aparece en una jugada a balón parado.", difficulty: 3 },
      { word: "Celebración de gol", hint: "Llega después de un momento importante.", difficulty: 2 },
      { word: "Fuera de juego", hint: "Es una regla muy discutida.", difficulty: 3 },
      { word: "VAR", hint: "Se usa cuando hay dudas.", difficulty: 3 }
    ]
  },
  {
    id: "pop-disney", emoji: "✨", title: "Pop & Disney", subtitle: "Territorio Laura · personajes muy reconocibles",
    cards: [
      { word: "Rapunzel", hint: "Protagonista de una película de Disney.", difficulty: 1 },
      { word: "Stitch", hint: "Personaje de Disney que no es humano.", difficulty: 1 },
      { word: "Mickey Mouse", hint: "Personaje clásico de Disney.", difficulty: 1 },
      { word: "Minnie Mouse", hint: "Personaje clásico de Disney.", difficulty: 1 },
      { word: "Olaf", hint: "Secundario muy reconocible de Disney.", difficulty: 1 },
      { word: "Elsa", hint: "Protagonista de una película musical de Disney.", difficulty: 1 },
      { word: "Simba", hint: "Protagonista de un clásico de Disney.", difficulty: 1 },
      { word: "Genio de Aladdín", hint: "Personaje mágico de un clásico de Disney.", difficulty: 2 },
      { word: "Ariel", hint: "Princesa de un clásico de Disney.", difficulty: 1 },
      { word: "Buzz Lightyear", hint: "Personaje de una saga de Pixar.", difficulty: 1 },
      { word: "Woody", hint: "Personaje de una saga de Pixar.", difficulty: 1 },
      { word: "Rayo McQueen", hint: "Protagonista de una saga de Pixar.", difficulty: 1 },
      { word: "Nemo", hint: "Protagonista de una película de Pixar.", difficulty: 1 },
      { word: "Dory", hint: "Acompaña al protagonista en una película de Pixar.", difficulty: 2 },
      { word: "Sulley", hint: "Personaje de una película sobre monstruos.", difficulty: 2 },
      { word: "Mike Wazowski", hint: "Personaje de una película sobre monstruos.", difficulty: 1 },
      { word: "Dumbo", hint: "Protagonista de un clásico antiguo de Disney.", difficulty: 1 },
      { word: "Aladdín", hint: "Protagonista de un clásico de Disney.", difficulty: 2 },
      { word: "Pinocho", hint: "Protagonista de un cuento llevado a Disney.", difficulty: 1 },
      { word: "Peter Pan", hint: "Personaje clásico de Disney.", difficulty: 2 },
      { word: "Campanilla", hint: "Personaje pequeño de un clásico Disney.", difficulty: 2 },
      { word: "Vaiana", hint: "Protagonista de una aventura de Disney.", difficulty: 2 },
      { word: "Blancanieves", hint: "Princesa de uno de los primeros clásicos.", difficulty: 2 },
      { word: "Cenicienta", hint: "Princesa de un clásico de Disney.", difficulty: 2 },
      { word: "Mulan", hint: "Heroína de un clásico de Disney.", difficulty: 3 }
    ]
  },
  {
    id: "series", emoji: "📺", title: "Series & TV", subtitle: "Series con una imagen o idea muy reconocible",
    cards: [
      { word: "Los Simpson", hint: "Serie de animación muy longeva.", difficulty: 1 },
      { word: "Bob Esponja", hint: "Serie infantil ambientada en un lugar peculiar.", difficulty: 1 },
      { word: "La Casa de Papel", hint: "Serie española muy conocida.", difficulty: 2 },
      { word: "Prison Break", hint: "Serie estadounidense de suspense.", difficulty: 2 },
      { word: "Stranger Things", hint: "Misterio con elementos sobrenaturales.", difficulty: 2 },
      { word: "Miércoles", hint: "Serie centrada en una familia muy famosa.", difficulty: 1 },
      { word: "Juego de Tronos", hint: "Fantasía épica de enorme éxito.", difficulty: 3 },
      { word: "The Walking Dead", hint: "Serie de supervivencia.", difficulty: 2 },
      { word: "El juego del calamar", hint: "Serie coreana de enorme éxito.", difficulty: 2 },
      { word: "Pokémon", hint: "Serie vinculada también a videojuegos.", difficulty: 1 },
      { word: "Doraemon", hint: "Serie infantil japonesa.", difficulty: 1 },
      { word: "Peppa Pig", hint: "Serie infantil de animación.", difficulty: 1 },
      { word: "South Park", hint: "Animación para adultos.", difficulty: 2 },
      { word: "Tom y Jerry", hint: "Clásico de animación.", difficulty: 1 },
      { word: "Scooby-Doo", hint: "Animación con misterios.", difficulty: 1 },
      { word: "Padre de familia", hint: "Comedia de animación para adultos.", difficulty: 3 },
      { word: "Breaking Bad", hint: "Drama sobre un cambio radical de vida.", difficulty: 3 },
      { word: "Los Picapiedra", hint: "Animación ambientada en otra época.", difficulty: 2 },
      { word: "La Pantera Rosa", hint: "Clásico de animación con un protagonista peculiar.", difficulty: 1 },
      { word: "Dragon Ball", hint: "Anime de acción muy conocido.", difficulty: 1 },
      { word: "Las Supernenas", hint: "Animación con protagonistas femeninas.", difficulty: 2 },
      { word: "Los Teletubbies", hint: "Programa infantil muy reconocible.", difficulty: 1 },
      { word: "La Patrulla Canina", hint: "Serie infantil centrada en un equipo.", difficulty: 1 },
      { word: "Mr. Bean", hint: "Comedia británica con poco diálogo.", difficulty: 2 },
      { word: "La que se avecina", hint: "Comedia española sobre vecinos.", difficulty: 3 }
    ]
  },
  {
    id: "peliculas", emoji: "🎬", title: "Películas", subtitle: "Cine con escenas y personajes muy visuales",
    cards: [
      { word: "Titanic", hint: "Romance basado en un hecho histórico.", difficulty: 1 },
      { word: "Shrek", hint: "Animación con humor para todas las edades.", difficulty: 1 },
      { word: "Jurassic Park", hint: "Aventura y ciencia ficción.", difficulty: 1 },
      { word: "Tiburón", hint: "Clásico de suspense ambientado en el mar.", difficulty: 1 },
      { word: "E.T.", hint: "Clásico de ciencia ficción de los 80.", difficulty: 2 },
      { word: "Cazafantasmas", hint: "Comedia de ciencia ficción con un equipo.", difficulty: 2 },
      { word: "El Grinch", hint: "Muy asociada a la Navidad.", difficulty: 1 },
      { word: "Star Wars", hint: "Saga de ciencia ficción.", difficulty: 2 },
      { word: "Piratas del Caribe", hint: "Saga de aventuras en el mar.", difficulty: 2 },
      { word: "101 Dálmatas", hint: "Clásico familiar de Disney.", difficulty: 1 },
      { word: "Jumanji", hint: "Aventura donde un juego tiene mucho peso.", difficulty: 3 },
      { word: "Up", hint: "Película de Pixar sobre un viaje inesperado.", difficulty: 1 },
      { word: "Ratatouille", hint: "Película de Pixar ambientada en París.", difficulty: 1 },
      { word: "Matrix", hint: "Ciencia ficción sobre una realidad engañosa.", difficulty: 3 },
      { word: "Rocky", hint: "Drama deportivo muy famoso.", difficulty: 2 },
      { word: "Barbie", hint: "Basada en una marca de juguetes.", difficulty: 1 },
      { word: "Los Minions", hint: "Saga de animación derivada de otra.", difficulty: 1 },
      { word: "Coco", hint: "Película de Pixar inspirada en México.", difficulty: 2 },
      { word: "Ice Age", hint: "Animación ambientada en la prehistoria.", difficulty: 2 },
      { word: "Kung Fu Panda", hint: "Animación con artes marciales.", difficulty: 1 },
      { word: "Madagascar", hint: "Animación protagonizada por animales.", difficulty: 2 },
      { word: "Buscando a Nemo", hint: "Película de Pixar ambientada bajo el agua.", difficulty: 2 },
      { word: "El Rey León", hint: "Clásico de Disney ambientado en África.", difficulty: 1 },
      { word: "Toy Story", hint: "Saga de Pixar sobre objetos con vida.", difficulty: 1 },
      { word: "Regreso al futuro", hint: "Clásico de ciencia ficción de los 80.", difficulty: 3 }
    ]
  },
  {
    id: "musica", emoji: "🎵", title: "Música", subtitle: "Instrumentos y escenas musicales fáciles de dibujar",
    cards: [
      { word: "Micrófono", hint: "Se usa tanto en directo como en estudio.", difficulty: 1 },
      { word: "Guitarra", hint: "Instrumento habitual en muchos estilos.", difficulty: 1 },
      { word: "Piano", hint: "Puede hacer melodía y acompañamiento.", difficulty: 1 },
      { word: "Batería", hint: "Suele marcar el ritmo.", difficulty: 1 },
      { word: "Auriculares", hint: "Sirven para escuchar sin molestar.", difficulty: 1 },
      { word: "Altavoz", hint: "Hace que todos puedan escuchar.", difficulty: 1 },
      { word: "DJ", hint: "Trabaja seleccionando y mezclando música.", difficulty: 2 },
      { word: "Concierto", hint: "Evento musical en directo.", difficulty: 2 },
      { word: "Festival de música", hint: "Evento en directo que puede durar días.", difficulty: 3 },
      { word: "Disco de vinilo", hint: "Formato físico para escuchar música.", difficulty: 1 },
      { word: "Karaoke", hint: "Actividad musical donde participa el público.", difficulty: 2 },
      { word: "Trompeta", hint: "Instrumento de viento usado en bandas.", difficulty: 2 },
      { word: "Saxofón", hint: "Instrumento de viento habitual en jazz.", difficulty: 2 },
      { word: "Violín", hint: "Muy presente en música clásica.", difficulty: 2 },
      { word: "Maracas", hint: "Instrumento de percusión manual.", difficulty: 1 },
      { word: "Flauta", hint: "Instrumento de viento ligero.", difficulty: 1 },
      { word: "Nota musical", hint: "Elemento básico de una partitura.", difficulty: 1 },
      { word: "Álbum de música", hint: "Agrupa varias canciones de un artista.", difficulty: 3 },
      { word: "Tocadiscos", hint: "Reproduce un formato físico de música.", difficulty: 2 },
      { word: "Bailar", hint: "Suele acompañar a la música.", difficulty: 2 },
      { word: "Cantante", hint: "Persona que interpreta canciones.", difficulty: 2 },
      { word: "Escenario", hint: "Lugar principal durante una actuación.", difficulty: 2 },
      { word: "Partitura", hint: "Sirve para leer una composición.", difficulty: 3 },
      { word: "Teclado musical", hint: "Instrumento electrónico muy usado en directo.", difficulty: 2 },
      { word: "Grammy", hint: "Premio importante de la industria musical.", difficulty: 3 }
    ]
  },
  {
    id: "sagas", emoji: "🦸", title: "Héroes & Sagas", subtitle: "Personajes con siluetas, poderes o símbolos claros",
    cards: [
      { word: "Spider-Man", hint: "Personaje de Marvel ligado a Nueva York.", difficulty: 1 },
      { word: "Iron Man", hint: "Personaje de Marvel con mucha tecnología.", difficulty: 1 },
      { word: "Hulk", hint: "Personaje de Marvel famoso por su fuerza.", difficulty: 1 },
      { word: "Thor", hint: "Personaje de Marvel inspirado en mitología.", difficulty: 1 },
      { word: "Capitán América", hint: "Personaje de Marvel asociado a Estados Unidos.", difficulty: 1 },
      { word: "Thanos", hint: "Gran villano del universo Marvel.", difficulty: 2 },
      { word: "Wolverine", hint: "Mutante muy famoso de Marvel.", difficulty: 1 },
      { word: "Deadpool", hint: "Personaje de Marvel conocido por su humor.", difficulty: 1 },
      { word: "Groot", hint: "Personaje de Guardianes de la Galaxia.", difficulty: 1 },
      { word: "Batman", hint: "Héroe de DC ligado a Gotham.", difficulty: 1 },
      { word: "Superman", hint: "Héroe clásico de DC.", difficulty: 1 },
      { word: "Wonder Woman", hint: "Heroína clásica de DC.", difficulty: 2 },
      { word: "Darth Vader", hint: "Villano de una saga espacial.", difficulty: 1 },
      { word: "Yoda", hint: "Maestro de una saga espacial.", difficulty: 1 },
      { word: "Harry Potter", hint: "Protagonista de una saga de magia.", difficulty: 1 },
      { word: "Voldemort", hint: "Villano principal de una saga de magia.", difficulty: 2 },
      { word: "Jack Sparrow", hint: "Personaje principal de una saga de piratas.", difficulty: 2 },
      { word: "Gollum", hint: "Personaje de una saga de fantasía.", difficulty: 3 },
      { word: "Sonic", hint: "Personaje clásico de videojuegos.", difficulty: 1 },
      { word: "Mario Bros", hint: "Personaje clásico de Nintendo.", difficulty: 1 },
      { word: "Lara Croft", hint: "Protagonista de videojuegos y cine.", difficulty: 3 },
      { word: "Indiana Jones", hint: "Aventurero de una saga clásica.", difficulty: 2 },
      { word: "Optimus Prime", hint: "Personaje principal de una saga de robots.", difficulty: 3 },
      { word: "Godzilla", hint: "Monstruo gigante de una saga japonesa.", difficulty: 1 },
      { word: "King Kong", hint: "Monstruo gigante clásico del cine.", difficulty: 1 }
    ]
  },
  {
    id: "casa-comida", emoji: "🍕", title: "Comida & Casa", subtitle: "Objetos cotidianos y comida muy visual",
    cards: [
      { word: "Pizza", hint: "Comida muy habitual para compartir.", difficulty: 1 },
      { word: "Hamburguesa", hint: "Comida rápida muy popular.", difficulty: 1 },
      { word: "Kebab", hint: "Comida callejera muy popular.", difficulty: 2 },
      { word: "Paella", hint: "Plato español típico para compartir.", difficulty: 2 },
      { word: "Sushi", hint: "Comida japonesa servida en pequeñas piezas.", difficulty: 2 },
      { word: "Croissant", hint: "Algo típico de desayuno o merienda.", difficulty: 1 },
      { word: "Helado", hint: "Postre frío.", difficulty: 1 },
      { word: "Palomitas", hint: "Snack muy asociado a una actividad de ocio.", difficulty: 1 },
      { word: "Huevo frito", hint: "Comida sencilla hecha en sartén.", difficulty: 1 },
      { word: "Espaguetis", hint: "Tipo de pasta.", difficulty: 1 },
      { word: "Tortilla de patatas", hint: "Plato español muy común.", difficulty: 2 },
      { word: "Taza de café", hint: "Objeto habitual en desayunos.", difficulty: 1 },
      { word: "Sofá", hint: "Mueble del salón.", difficulty: 1 },
      { word: "Cama", hint: "Mueble del dormitorio.", difficulty: 1 },
      { word: "Ducha", hint: "Está en el baño.", difficulty: 1 },
      { word: "Lavadora", hint: "Electrodoméstico relacionado con la ropa.", difficulty: 1 },
      { word: "Nevera", hint: "Electrodoméstico de la cocina.", difficulty: 1 },
      { word: "Aspiradora", hint: "Aparato para limpiar.", difficulty: 2 },
      { word: "Inodoro", hint: "Elemento del baño.", difficulty: 1 },
      { word: "Lámpara", hint: "Objeto relacionado con la iluminación.", difficulty: 1 },
      { word: "Llave", hint: "Objeto pequeño que solemos llevar encima.", difficulty: 1 },
      { word: "Puerta", hint: "Elemento que separa espacios.", difficulty: 1 },
      { word: "Tostadora", hint: "Pequeño electrodoméstico de cocina.", difficulty: 2 },
      { word: "Microondas", hint: "Electrodoméstico de cocina.", difficulty: 2 },
      { word: "Paraguas", hint: "Útil cuando hace mal tiempo.", difficulty: 1 }
    ]
  },
  {
    id: "internet-juegos", emoji: "🎮", title: "Internet & Juegos", subtitle: "Videojuegos, dispositivos y símbolos muy visuales",
    cards: [
      { word: "Mando de PlayStation", hint: "Accesorio para jugar.", difficulty: 1 },
      { word: "Nintendo Switch", hint: "Consola moderna muy popular.", difficulty: 2 },
      { word: "Super Mario", hint: "Personaje clásico de Nintendo.", difficulty: 1 },
      { word: "Luigi", hint: "Personaje clásico de Nintendo.", difficulty: 2 },
      { word: "Pikachu", hint: "Personaje de una saga japonesa.", difficulty: 1 },
      { word: "Minecraft", hint: "Videojuego de construcción y exploración.", difficulty: 1 },
      { word: "Fortnite", hint: "Videojuego multijugador muy popular.", difficulty: 3 },
      { word: "GTA", hint: "Saga de videojuegos de mundo abierto.", difficulty: 3 },
      { word: "Among Us", hint: "Juego multijugador de deducción.", difficulty: 1 },
      { word: "Pac-Man", hint: "Personaje clásico de arcade.", difficulty: 1 },
      { word: "Tetris", hint: "Videojuego clásico de puzles.", difficulty: 1 },
      { word: "Selfie", hint: "Tipo de foto común en redes.", difficulty: 1 },
      { word: "Emoji", hint: "Elemento usado en mensajes y redes.", difficulty: 1 },
      { word: "Wi-Fi", hint: "Tecnología presente en casi cualquier casa.", difficulty: 1 },
      { word: "Código QR", hint: "Se escanea con el móvil.", difficulty: 2 },
      { word: "Ordenador portátil", hint: "Dispositivo que puede usarse en cualquier sitio.", difficulty: 1 },
      { word: "Teléfono móvil", hint: "Dispositivo que llevamos casi siempre encima.", difficulty: 1 },
      { word: "Robot", hint: "Máquina capaz de realizar tareas.", difficulty: 1 },
      { word: "Realidad virtual", hint: "Tecnología para entrar en un entorno digital.", difficulty: 2 },
      { word: "Videollamada", hint: "Forma de comunicarse a distancia.", difficulty: 2 },
      { word: "Consola de videojuegos", hint: "Dispositivo pensado para jugar.", difficulty: 2 },
      { word: "Cámara web", hint: "Accesorio habitual en videollamadas.", difficulty: 2 },
      { word: "Dron", hint: "Dispositivo controlado a distancia.", difficulty: 2 },
      { word: "Máquina arcade", hint: "Clásico de los salones recreativos.", difficulty: 3 },
      { word: "Silla gaming", hint: "Mueble habitual en setups de juego.", difficulty: 2 }
    ]
  },
  {
    id: "mix", emoji: "🎲", title: "Mix", subtitle: "Cosas de toda la vida, sin saber qué viene después",
    cards: [
      { word: "Avión", hint: "Transporte para largas distancias.", difficulty: 1 },
      { word: "Playa", hint: "Lugar típico de vacaciones.", difficulty: 1 },
      { word: "Camping", hint: "Plan al aire libre.", difficulty: 2 },
      { word: "Boda", hint: "Celebración importante de pareja.", difficulty: 2 },
      { word: "Cumpleaños", hint: "Celebración que ocurre una vez al año.", difficulty: 1 },
      { word: "Gimnasio", hint: "Lugar para entrenar.", difficulty: 2 },
      { word: "Discoteca", hint: "Lugar de ocio nocturno.", difficulty: 2 },
      { word: "Taxi", hint: "Transporte urbano.", difficulty: 1 },
      { word: "Metro", hint: "Transporte público de ciudad.", difficulty: 2 },
      { word: "Hospital", hint: "Lugar relacionado con la salud.", difficulty: 1 },
      { word: "Policía", hint: "Profesión de servicio público.", difficulty: 1 },
      { word: "Bombero", hint: "Profesión de emergencia.", difficulty: 1 },
      { word: "Pirata", hint: "Personaje típico de aventuras.", difficulty: 1 },
      { word: "Astronauta", hint: "Profesión relacionada con el espacio.", difficulty: 1 },
      { word: "Dinosaurio", hint: "Ser de una época muy antigua.", difficulty: 1 },
      { word: "Fantasma", hint: "Personaje típico de historias de miedo.", difficulty: 1 },
      { word: "Alien", hint: "Ser típico de ciencia ficción.", difficulty: 1 },
      { word: "Volcán", hint: "Elemento natural peligroso.", difficulty: 1 },
      { word: "Arcoíris", hint: "Fenómeno relacionado con el tiempo.", difficulty: 1 },
      { word: "Muñeco de nieve", hint: "Se suele hacer en invierno.", difficulty: 1 },
      { word: "Bicicleta", hint: "Transporte sin motor.", difficulty: 1 },
      { word: "Montaña rusa", hint: "Atracción de parque temático.", difficulty: 2 },
      { word: "Castillo", hint: "Edificio típico de cuentos e historia.", difficulty: 1 },
      { word: "Isla desierta", hint: "Un lugar lejos de todo.", difficulty: 2 },
      { word: "Coche de carreras", hint: "Vehículo preparado para competir.", difficulty: 1 }
    ]
  }
];

window.JAVIEATS_TABOO_SECTIONS = [
  {
    id: "futbol", emoji: "⚽", title: "Fútbol",
    cards: [
      { word: "Kylian Mbappé", banned: ["Real Madrid","Francia","delantero","fútbol"], difficulty: 1 },
      { word: "Lamine Yamal", banned: ["Barcelona","España","joven","fútbol"], difficulty: 1 },
      { word: "Cristiano Ronaldo", banned: ["Portugal","Real Madrid","Messi","fútbol"], difficulty: 1 },
      { word: "Lionel Messi", banned: ["Argentina","Barcelona","Cristiano","fútbol"], difficulty: 1 },
      { word: "Vinícius Jr.", banned: ["Real Madrid","Brasil","extremo"], difficulty: 2 },
      { word: "Erling Haaland", banned: ["Manchester City","Noruega","delantero","fútbol"], difficulty: 1 },
      { word: "Jude Bellingham", banned: ["Real Madrid","Inglaterra","centrocampista"], difficulty: 2 },
      { word: "Rodri", banned: ["Manchester City","España"], difficulty: 3 },
      { word: "Antoine Griezmann", banned: ["Atlético de Madrid","Francia","delantero"], difficulty: 2 },
      { word: "Pedri", banned: ["Barcelona","Canarias"], difficulty: 3 },
      { word: "Neymar", banned: ["Brasil","PSG","Barcelona","fútbol"], difficulty: 1 },
      { word: "Robert Lewandowski", banned: ["Barcelona","Polonia","delantero"], difficulty: 2 },
      { word: "Sergio Ramos", banned: ["defensa","Real Madrid","Sevilla"], difficulty: 2 },
      { word: "Luka Modrić", banned: ["Croacia","Real Madrid"], difficulty: 3 },
      { word: "Andrés Iniesta", banned: ["España","Barcelona","Mundial"], difficulty: 2 },
      { word: "Pep Guardiola", banned: ["entrenador","Manchester City","Barcelona"], difficulty: 2 },
      { word: "José Mourinho", banned: ["entrenador","Real Madrid","Portugal"], difficulty: 2 },
      { word: "Diego Simeone", banned: ["Atlético de Madrid","entrenador","Cholo"], difficulty: 2 },
      { word: "Carlo Ancelotti", banned: ["entrenador","Real Madrid"], difficulty: 3 },
      { word: "Real Madrid", banned: ["Bernabéu","blanco","Champions","fútbol"], difficulty: 1 },
      { word: "FC Barcelona", banned: ["Camp Nou","azulgrana","Cataluña","fútbol"], difficulty: 1 },
      { word: "Atlético de Madrid", banned: ["Metropolitano","Simeone","rojiblanco"], difficulty: 2 },
      { word: "Champions League", banned: ["Europa","orejona","clubes","fútbol"], difficulty: 1 },
      { word: "Copa del Mundo", banned: ["selecciones","Mundial","FIFA","fútbol"], difficulty: 1 },
      { word: "VAR", banned: ["árbitro","vídeo","revisión","fútbol"], difficulty: 1 }
    ]
  },
  {
    id: "pop-disney", emoji: "✨", title: "Pop & Disney",
    cards: [
      { word: "TINI", banned: ["Violetta","Argentina","cantante","música"], difficulty: 1 },
      { word: "Violetta", banned: ["Disney","TINI","serie"], difficulty: 1 },
      { word: "Emilia", banned: ["Argentina","TINI","cantante"], difficulty: 1 },
      { word: "Justin Bieber", banned: ["Canadá","Baby","Hailey","cantante"], difficulty: 1 },
      { word: "Rapunzel", banned: ["Enredados","pelo","princesa","Disney"], difficulty: 1 },
      { word: "Flynn Rider", banned: ["Enredados","Rapunzel"], difficulty: 3 },
      { word: "Stitch", banned: ["Lilo","azul","alien","Disney"], difficulty: 1 },
      { word: "Elsa", banned: ["Frozen","hielo","Anna","Disney"], difficulty: 1 },
      { word: "Olaf", banned: ["Frozen","muñeco de nieve","Elsa","Disney"], difficulty: 1 },
      { word: "Simba", banned: ["El Rey León","Mufasa","león","Disney"], difficulty: 1 },
      { word: "Genio", banned: ["Aladdín","lámpara","azul"], difficulty: 2 },
      { word: "Ariel", banned: ["La Sirenita","mar","pelirroja","Disney"], difficulty: 1 },
      { word: "Buzz Lightyear", banned: ["Toy Story","espacio","Woody","Disney"], difficulty: 1 },
      { word: "Woody", banned: ["Toy Story","vaquero","Buzz","Disney"], difficulty: 1 },
      { word: "Rayo McQueen", banned: ["Cars","coche","carreras","Disney"], difficulty: 1 },
      { word: "Hannah Montana", banned: ["Miley Cyrus","Disney","doble vida"], difficulty: 2 },
      { word: "High School Musical", banned: ["Troy","Gabriella","Disney"], difficulty: 2 },
      { word: "Camp Rock", banned: ["Demi Lovato","Jonas Brothers"], difficulty: 3 },
      { word: "Miley Cyrus", banned: ["Hannah Montana","cantante","Disney"], difficulty: 2 },
      { word: "Selena Gomez", banned: ["Disney","cantante","Wizards"], difficulty: 2 },
      { word: "Demi Lovato", banned: ["Camp Rock","Disney"], difficulty: 3 },
      { word: "Jonas Brothers", banned: ["hermanos","Disney"], difficulty: 3 },
      { word: "Mickey Mouse", banned: ["Disney","ratón","Minnie"], difficulty: 1 },
      { word: "Cenicienta", banned: ["princesa","zapatilla","medianoche"], difficulty: 2 },
      { word: "Vaiana", banned: ["Disney","océano"], difficulty: 3 }
    ]
  },
  {
    id: "series", emoji: "📺", title: "Series",
    cards: [
      { word: "La Casa de Papel", banned: ["atraco","Profesor","Netflix","serie"], difficulty: 1 },
      { word: "El Profesor", banned: ["La Casa de Papel","atraco","Sergio","serie"], difficulty: 1 },
      { word: "Tokio", banned: ["La Casa de Papel","Úrsula Corberó","serie"], difficulty: 2 },
      { word: "Berlín", banned: ["La Casa de Papel","Profesor","Andrés"], difficulty: 2 },
      { word: "Nairobi", banned: ["La Casa de Papel","Alba Flores","dinero"], difficulty: 2 },
      { word: "Río", banned: ["La Casa de Papel","Tokio"], difficulty: 3 },
      { word: "Outer Banks", banned: ["Pogues","tesoro","John B","serie"], difficulty: 1 },
      { word: "John B", banned: ["Outer Banks","Sarah"], difficulty: 1 },
      { word: "Sarah Cameron", banned: ["Outer Banks","John B"], difficulty: 2 },
      { word: "JJ Maybank", banned: ["Outer Banks","John B"], difficulty: 2 },
      { word: "Rafe Cameron", banned: ["Outer Banks","Sarah"], difficulty: 2 },
      { word: "Kiara", banned: ["Outer Banks","Pogues"], difficulty: 2 },
      { word: "Prison Break", banned: ["cárcel","fuga","Michael Scofield","serie"], difficulty: 1 },
      { word: "Michael Scofield", banned: ["Prison Break","tatuaje","Lincoln","serie"], difficulty: 1 },
      { word: "Lincoln Burrows", banned: ["Prison Break","Michael"], difficulty: 3 },
      { word: "Vis a Vis", banned: ["cárcel","Macarena","Zulema"], difficulty: 2 },
      { word: "Zulema", banned: ["Vis a Vis","Najwa Nimri"], difficulty: 3 },
      { word: "Gossip Girl", banned: ["Blair","Serena","Nueva York","serie"], difficulty: 1 },
      { word: "Blair Waldorf", banned: ["Gossip Girl","Serena"], difficulty: 3 },
      { word: "Breaking Bad", banned: ["Walter White","metanfetamina","química","serie"], difficulty: 1 },
      { word: "Walter White", banned: ["Breaking Bad","Heisenberg","profesor"], difficulty: 2 },
      { word: "Stranger Things", banned: ["Once","Hawkins","Demogorgon","serie"], difficulty: 1 },
      { word: "Miércoles", banned: ["Addams","Netflix","Thing","serie"], difficulty: 1 },
      { word: "Los Simpson", banned: ["Homer","Springfield","amarillos","serie"], difficulty: 1 },
      { word: "La que se avecina", banned: ["Montepinár","vecinos"], difficulty: 3 }
    ]
  },
  {
    id: "peliculas", emoji: "🎬", title: "Películas",
    cards: [
      { word: "Titanic", banned: ["barco","iceberg","Jack","película"], difficulty: 1 },
      { word: "Shrek", banned: ["ogro","Fiona","Burro","película"], difficulty: 1 },
      { word: "Jurassic Park", banned: ["dinosaurios","isla","Spielberg","película"], difficulty: 1 },
      { word: "Avatar", banned: ["Pandora","Na'vi","azul","película"], difficulty: 1 },
      { word: "Gladiator", banned: ["Roma","Máximo"], difficulty: 3 },
      { word: "Matrix", banned: ["Neo","pastilla","realidad","película"], difficulty: 1 },
      { word: "Rocky", banned: ["boxeo","Stallone","Filadelfia","película"], difficulty: 1 },
      { word: "Solo en casa", banned: ["Kevin","Navidad","ladrones","película"], difficulty: 1 },
      { word: "El Señor de los Anillos", banned: ["anillo","Frodo","Mordor"], difficulty: 2 },
      { word: "Piratas del Caribe", banned: ["Jack Sparrow","piratas","barco","película"], difficulty: 1 },
      { word: "Joker", banned: ["payaso","Batman","Gotham","película"], difficulty: 1 },
      { word: "Barbie", banned: ["rosa","muñeca","Ken","película"], difficulty: 1 },
      { word: "Oppenheimer", banned: ["bomba","nuclear"], difficulty: 3 },
      { word: "El lobo de Wall Street", banned: ["DiCaprio","bolsa","Jordan Belfort"], difficulty: 2 },
      { word: "Crepúsculo", banned: ["vampiro","Bella","Edward"], difficulty: 2 },
      { word: "Los juegos del hambre", banned: ["Katniss","distritos","arco","película"], difficulty: 1 },
      { word: "Top Gun", banned: ["aviones","Tom Cruise","piloto","película"], difficulty: 1 },
      { word: "Misión Imposible", banned: ["Tom Cruise","Ethan Hunt","espía"], difficulty: 2 },
      { word: "El Padrino", banned: ["mafia","Corleone"], difficulty: 3 },
      { word: "Tiburón", banned: ["Spielberg","mar","playa","película"], difficulty: 1 },
      { word: "Regreso al futuro", banned: ["DeLorean","Marty","tiempo","película"], difficulty: 1 },
      { word: "Forrest Gump", banned: ["Tom Hanks","correr","banco"], difficulty: 2 },
      { word: "E.T.", banned: ["alien","bicicleta","teléfono","película"], difficulty: 1 },
      { word: "Karate Kid", banned: ["karate","Miyagi"], difficulty: 3 },
      { word: "Resacón en Las Vegas", banned: ["Las Vegas","despedida"], difficulty: 3 }
    ]
  },
  {
    id: "musica", emoji: "🎵", title: "Música",
    cards: [
      { word: "Quevedo", banned: ["Canarias","Bizarrap","Quédate","música"], difficulty: 1 },
      { word: "Bad Bunny", banned: ["Puerto Rico","conejo","reguetón","música"], difficulty: 1 },
      { word: "Eladio Carrión", banned: ["Puerto Rico","trap","rapero"], difficulty: 2 },
      { word: "La Pantera", banned: ["Canarias","rapero"], difficulty: 3 },
      { word: "Lucho RK", banned: ["Canarias","cantante"], difficulty: 3 },
      { word: "Feid", banned: ["Colombia","verde","Ferxxo","música"], difficulty: 1 },
      { word: "Myke Towers", banned: ["Puerto Rico","rapero","La Playa","música"], difficulty: 1 },
      { word: "Rauw Alejandro", banned: ["Puerto Rico","Rosalía","Todo de Ti","música"], difficulty: 1 },
      { word: "Mora", banned: ["Puerto Rico","reguetón","Memorias"], difficulty: 2 },
      { word: "Duki", banned: ["Argentina","trap","Bizarrap","música"], difficulty: 1 },
      { word: "Bizarrap", banned: ["sesiones","gorra","productor","música"], difficulty: 1 },
      { word: "Karol G", banned: ["Colombia","Bichota","cantante","música"], difficulty: 1 },
      { word: "Anuel AA", banned: ["Puerto Rico","Real Hasta La Muerte","reguetón","música"], difficulty: 1 },
      { word: "Ozuna", banned: ["Puerto Rico","reguetón","Negrito de ojos claros"], difficulty: 2 },
      { word: "J Balvin", banned: ["Colombia","reguetón","Mi Gente"], difficulty: 2 },
      { word: "Maluma", banned: ["Colombia","Hawái","cantante"], difficulty: 2 },
      { word: "Young Miko", banned: ["Puerto Rico","rapera","trap"], difficulty: 2 },
      { word: "Omar Courtz", banned: ["Puerto Rico","reguetón"], difficulty: 3 },
      { word: "Saiko", banned: ["Granada","Polaris"], difficulty: 3 },
      { word: "JC Reyes", banned: ["Sevilla","rapero"], difficulty: 3 },
      { word: "Daddy Yankee", banned: ["Gasolina","Puerto Rico","reguetón","música"], difficulty: 1 },
      { word: "Don Omar", banned: ["Dale Don Dale","Puerto Rico","reguetón"], difficulty: 2 },
      { word: "Rosalía", banned: ["Motomami","Barcelona","cantante","música"], difficulty: 1 },
      { word: "Aitana", banned: ["Operación Triunfo","España","cantante","música"], difficulty: 1 },
      { word: "Lola Índigo", banned: ["Granada","bailarina","cantante"], difficulty: 2 }
    ]
  },
  {
    id: "sagas", emoji: "🦸", title: "Marvel & Sagas",
    cards: [
      { word: "Los Vengadores", banned: ["Marvel","superhéroes","Thanos","saga"], difficulty: 1 },
      { word: "Iron Man", banned: ["Tony Stark","armadura","Marvel","saga"], difficulty: 1 },
      { word: "Spider-Man", banned: ["Peter Parker","araña","Marvel","saga"], difficulty: 1 },
      { word: "Hulk", banned: ["verde","Bruce Banner","Marvel","saga"], difficulty: 1 },
      { word: "Thor", banned: ["martillo","Asgard","Marvel","saga"], difficulty: 1 },
      { word: "Capitán América", banned: ["escudo","Steve Rogers","Marvel","saga"], difficulty: 1 },
      { word: "Thanos", banned: ["guantelete","gemas","Marvel","saga"], difficulty: 1 },
      { word: "Doctor Strange", banned: ["portal","magia","Marvel"], difficulty: 2 },
      { word: "Loki", banned: ["Thor","Asgard","engaño"], difficulty: 2 },
      { word: "Deadpool", banned: ["rojo","Marvel","Ryan Reynolds","saga"], difficulty: 1 },
      { word: "Wolverine", banned: ["garras","X-Men","Logan"], difficulty: 2 },
      { word: "Fast & Furious", banned: ["coches","Toretto","familia","saga"], difficulty: 1 },
      { word: "Dominic Toretto", banned: ["Fast & Furious","Vin Diesel","familia","saga"], difficulty: 1 },
      { word: "Brian O'Conner", banned: ["Fast & Furious","Paul Walker"], difficulty: 3 },
      { word: "Harry Potter", banned: ["Hogwarts","mago","Voldemort","saga"], difficulty: 1 },
      { word: "Voldemort", banned: ["Harry Potter","nariz","villano","saga"], difficulty: 1 },
      { word: "Hermione Granger", banned: ["Harry Potter","Hogwarts"], difficulty: 3 },
      { word: "Star Wars", banned: ["Jedi","espacio","Darth Vader","saga"], difficulty: 1 },
      { word: "Darth Vader", banned: ["Star Wars","Luke","negro","saga"], difficulty: 1 },
      { word: "Yoda", banned: ["Star Wars","verde","Jedi","saga"], difficulty: 1 },
      { word: "Jack Sparrow", banned: ["Piratas del Caribe","Johnny Depp","pirata"], difficulty: 2 },
      { word: "Transformers", banned: ["robots","Optimus Prime","coches"], difficulty: 2 },
      { word: "Frodo", banned: ["anillo","hobbit"], difficulty: 3 },
      { word: "Gollum", banned: ["anillo","precioso"], difficulty: 3 },
      { word: "Katniss Everdeen", banned: ["Juegos del Hambre","arco"], difficulty: 3 }
    ]
  },
  {
    id: "famosos", emoji: "🌟", title: "Famosos & públicos",
    cards: [
      { word: "Donald Trump", banned: ["Estados Unidos","presidente","republicano","política"], difficulty: 1 },
      { word: "Pedro Sánchez", banned: ["presidente","España","PSOE","política"], difficulty: 1 },
      { word: "Javier Milei", banned: ["Argentina","presidente","motosierra"], difficulty: 2 },
      { word: "Elon Musk", banned: ["Tesla","SpaceX","X","famoso"], difficulty: 1 },
      { word: "Jeff Bezos", banned: ["Amazon","multimillonario"], difficulty: 3 },
      { word: "Mark Zuckerberg", banned: ["Facebook","Meta","Instagram"], difficulty: 2 },
      { word: "Felipe VI", banned: ["rey","España"], difficulty: 3 },
      { word: "Letizia Ortiz", banned: ["reina","España"], difficulty: 3 },
      { word: "Ibai Llanos", banned: ["streamer","Twitch","Velada","famoso"], difficulty: 1 },
      { word: "David Broncano", banned: ["La Revuelta","presentador","televisión"], difficulty: 2 },
      { word: "MrBeast", banned: ["YouTube","retos","dinero","famoso"], difficulty: 1 },
      { word: "Shakira", banned: ["Colombia","Piqué","cantante","famoso"], difficulty: 1 },
      { word: "Taylor Swift", banned: ["Estados Unidos","Eras Tour","cantante","famoso"], difficulty: 1 },
      { word: "Beyoncé", banned: ["cantante","Jay-Z","Estados Unidos"], difficulty: 2 },
      { word: "Rihanna", banned: ["Barbados","cantante","Fenty"], difficulty: 2 },
      { word: "Dwayne Johnson", banned: ["La Roca","actor","lucha libre"], difficulty: 2 },
      { word: "Leonardo DiCaprio", banned: ["Titanic","actor","Oscar","famoso"], difficulty: 1 },
      { word: "Will Smith", banned: ["actor","Oscar","El Príncipe de Bel-Air","famoso"], difficulty: 1 },
      { word: "Tom Cruise", banned: ["Misión Imposible","actor","Top Gun","famoso"], difficulty: 1 },
      { word: "Kim Kardashian", banned: ["reality","Kanye West","familia"], difficulty: 2 },
      { word: "Zendaya", banned: ["actriz","Euphoria","Spider-Man"], difficulty: 2 },
      { word: "Jenna Ortega", banned: ["Miércoles","actriz"], difficulty: 3 },
      { word: "Pedro Pascal", banned: ["actor","The Last of Us"], difficulty: 3 },
      { word: "Georgina Rodríguez", banned: ["Cristiano Ronaldo","modelo","Netflix","famoso"], difficulty: 1 },
      { word: "Rafa Nadal", banned: ["tenis","Mallorca","Roland Garros","famoso"], difficulty: 1 }
    ]
  },
  {
    id: "tendencias", emoji: "🔥", title: "Internet & Tendencias",
    cards: [
      { word: "ChatGPT", banned: ["OpenAI","inteligencia artificial","chatbot","internet"], difficulty: 1 },
      { word: "TikTok", banned: ["vídeos","vertical","ByteDance","internet"], difficulty: 1 },
      { word: "Instagram", banned: ["Meta","stories","fotos","internet"], difficulty: 1 },
      { word: "Twitch", banned: ["streaming","directos","Amazon","internet"], difficulty: 1 },
      { word: "YouTube", banned: ["Google","vídeos","canal","internet"], difficulty: 1 },
      { word: "Netflix", banned: ["series","streaming","películas","internet"], difficulty: 1 },
      { word: "Spotify", banned: ["música","streaming","playlist","internet"], difficulty: 1 },
      { word: "WhatsApp", banned: ["mensajes","Meta","chat","internet"], difficulty: 1 },
      { word: "Meme", banned: ["internet","viral","imagen"], difficulty: 1 },
      { word: "Influencer", banned: ["redes sociales","seguidores","contenido","internet"], difficulty: 1 },
      { word: "Streamer", banned: ["directo","Twitch","cámara","internet"], difficulty: 1 },
      { word: "Podcast", banned: ["audio","episodios","micrófono","internet"], difficulty: 1 },
      { word: "Deepfake", banned: ["IA","vídeo"], difficulty: 3 },
      { word: "ASMR", banned: ["sonidos","susurros"], difficulty: 3 },
      { word: "Unboxing", banned: ["caja","vídeo"], difficulty: 3 },
      { word: "Rubius", banned: ["YouTube","streamer","España"], difficulty: 2 },
      { word: "Plex", banned: ["streamer","YouTube"], difficulty: 3 },
      { word: "AuronPlay", banned: ["streamer","Twitch","YouTube"], difficulty: 2 },
      { word: "TheGrefg", banned: ["streamer","Murcia","Fortnite"], difficulty: 2 },
      { word: "IlloJuan", banned: ["streamer","Málaga","Twitch"], difficulty: 2 },
      { word: "IShowSpeed", banned: ["streamer","Cristiano Ronaldo","Estados Unidos"], difficulty: 2 },
      { word: "La Velada del Año", banned: ["Ibai","boxeo","streamers","internet"], difficulty: 1 },
      { word: "Kings League", banned: ["Piqué","fútbol","presidentes","internet"], difficulty: 1 },
      { word: "Judeline", banned: ["cantante","España"], difficulty: 3 },
      { word: "Rusowsky", banned: ["artista","España"], difficulty: 3 }
    ]
  },
  {
    id: "mix", emoji: "🎲", title: "Mix",
    cards: [
      { word: "Mercadona", banned: ["supermercado","Hacendado","Juan Roig"], difficulty: 1 },
      { word: "McDonald's", banned: ["hamburguesa","Big Mac","comida rápida"], difficulty: 1 },
      { word: "Kebab", banned: ["carne","durum"], difficulty: 3 },
      { word: "Paella", banned: ["arroz","Valencia","comida"], difficulty: 2 },
      { word: "Gimnasio", banned: ["pesas","entrenar","máquinas"], difficulty: 1 },
      { word: "Discoteca", banned: ["baile","noche","DJ"], difficulty: 1 },
      { word: "Aeropuerto", banned: ["avión","maleta","viaje"], difficulty: 1 },
      { word: "Boda", banned: ["novios","anillos","casarse"], difficulty: 1 },
      { word: "Resaca", banned: ["alcohol","mañana"], difficulty: 3 },
      { word: "Guardia Civil", banned: ["policía","España"], difficulty: 3 },
      { word: "Fórmula 1", banned: ["coches","circuito","piloto"], difficulty: 1 },
      { word: "Tinder", banned: ["citas","match","aplicación"], difficulty: 1 },
      { word: "Amazon", banned: ["compras","Bezos","paquetes"], difficulty: 1 },
      { word: "IKEA", banned: ["muebles","Suecia","montar"], difficulty: 1 },
      { word: "Wallapop", banned: ["segunda mano","comprar","vender"], difficulty: 1 },
      { word: "Vinted", banned: ["ropa","segunda mano","vender"], difficulty: 1 },
      { word: "PlayStation", banned: ["Sony","consola","mando"], difficulty: 1 },
      { word: "Nintendo Switch", banned: ["Nintendo","consola","Joy-Con"], difficulty: 1 },
      { word: "Pikachu", banned: ["Pokémon","amarillo","eléctrico"], difficulty: 1 },
      { word: "GTA", banned: ["Rockstar","videojuego","coches"], difficulty: 1 },
      { word: "Minecraft", banned: ["bloques","Steve","videojuego"], difficulty: 1 },
      { word: "Fortnite", banned: ["Battle Royale","Epic Games","videojuego"], difficulty: 1 },
      { word: "Monopoly", banned: ["tablero","dinero","casas"], difficulty: 1 },
      { word: "Lotería", banned: ["números","premio"], difficulty: 3 },
      { word: "Festival", banned: ["música","conciertos"], difficulty: 3 }
    ]
  }
];
