
create table private.nuestro24_moments (
  id bigint generated by default as identity primary key,
  edition_date date not null,
  moment_date date not null,
  sort_order integer not null,
  kind text not null check (kind in ('memory','plan','app','special')),
  visual_key text not null check (visual_key ~ '^[a-z0-9-]+$'),
  eyebrow text not null default '',
  title text not null check (char_length(btrim(title)) between 1 and 140),
  body text not null default '' check (char_length(body) <= 1200),
  source_type text check (source_type in ('memory','proposal','curated','code')),
  source_id uuid,
  photo_path text,
  created_at timestamptz not null default now(),
  unique (edition_date, sort_order),
  check (extract(day from edition_date) = 24),
  check (moment_date > (edition_date - interval '1 month')::date and moment_date <= edition_date)
);

alter table private.nuestro24_moments enable row level security;
revoke all on private.nuestro24_moments from public, anon, authenticated;

insert into private.nuestro24_moments
  (edition_date, moment_date, sort_order, kind, visual_key, eyebrow, title, body, source_type, source_id, photo_path)
select
  date '2026-09-24', r.fecha, 10, 'memory', 'reunion', '31 de agosto',
  r.titulo, r.descripcion, 'memory', r.id,
  r.image_paths[2]
from public.recuerdos_app r
where r.fecha = date '2026-08-31'
  and lower(r.titulo) like '%niña%volvió%ciudad%'
order by r.created_at
limit 1;

insert into private.nuestro24_moments
  (edition_date, moment_date, sort_order, kind, visual_key, eyebrow, title, body, source_type)
values
  (date '2026-09-24', date '2026-09-01', 20, 'plan', 'home', '1 de septiembre',
   'Nos seguíamos echando de menos',
   'Nos seguíamos echando de menos y no tardamos mucho en volver a vernos. El 1 de septiembre volví a su casa a verla y a pasar otro ratito juntos.',
   'curated'),
  (date '2026-09-24', date '2026-09-12', 30, 'app', 'life', '12 de septiembre',
   'Nuestra Vida llegó a JaviEats',
   'Nuestra Vida se estrenó en JaviEats como una experiencia propia dentro de la aplicación.',
   'code');

insert into private.nuestro24_moments
  (edition_date, moment_date, sort_order, kind, visual_key, eyebrow, title, body, source_type, source_id)
select
  date '2026-09-24', p.plan_date, 40, 'plan', 'sunset', '16 de septiembre',
  'Uno de los últimos atardeceres del verano',
  'Nos apetecía hacer algo diferente y nos fuimos a ver uno de los últimos atardeceres del verano. De paso Laura vio por primera vez, el mejor estadio del mundo, el estadio de Vallecas.',
  'proposal', p.id
from public.propuestas p
where p.plan_date = date '2026-09-16'
  and p.status in ('confirmada','realizada')
  and lower(coalesce(p.note,'')) like '%atardecer%'
order by p.created_at
limit 1;

insert into private.nuestro24_moments
  (edition_date, moment_date, sort_order, kind, visual_key, eyebrow, title, body, source_type)
values
  (date '2026-09-24', date '2026-09-19', 50, 'plan', 'together', '19 de septiembre',
   'Antiresaca, previa y muchos mimos',
   'Esa tarde sirvió de antiresaca a Laura y a Javi de previa, e hicimos lo que mejor sabemos hacer, darnos mimos y querernos mucho, después de picarnos el uno al otro pero siempre con mucho amor. También tomamos algo y probamos juntos Entre tú y yo.',
   'curated'),
  (date '2026-09-24', date '2026-09-20', 60, 'plan', 'dogs', '20 de septiembre',
   'Los miembros más exigentes de la familia',
   'Fue un plan express, Laura estaba perdida por Madrid y la recogí y fuimos a que conociese a los perritos, ya ha conocido a los miembros más exigentes de la familia.',
   'curated');

insert into private.nuestro24_moments
  (edition_date, moment_date, sort_order, kind, visual_key, eyebrow, title, body, source_type, source_id)
select
  date '2026-09-24', r.fecha, 70, 'special', 'flowers', '21 de septiembre',
  r.titulo, r.descripcion, 'memory', r.id
from public.recuerdos_app r
where r.fecha = date '2026-09-21'
  and r.legacy_key = '2026-09-21-yellow-flowers'
order by r.created_at
limit 1;

insert into private.nuestro24_moments
  (edition_date, moment_date, sort_order, kind, visual_key, eyebrow, title, body, source_type, source_id)
select
  date '2026-09-24', p.plan_date, 80, 'plan', 'bowling', '24 de septiembre',
  'Quién sabe qué deparará la tarde',
  'El plan inicial es ir a jugar a los bolos, tomarse un helado y darnos muchos muchos mimos. Pero como Laura fluye mucho y Javi está aprendiendo de la mejor, quién sabe qué deparará la tarde.',
  'proposal', p.id
from public.propuestas p
where p.plan_date = date '2026-09-24'
  and p.status in ('confirmada','realizada')
  and lower(coalesce(p.note,'')) like '%helado%'
order by p.created_at
limit 1;

create or replace function private.nuestro24_snapshot(p_day date)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  c private.nuestro24_settings%rowtype;
  lower_day date := (p_day - interval '1 month')::date;
  lower_at timestamptz := lower_day::timestamp at time zone 'Europe/Madrid';
  upper_at timestamptz := p_day::timestamp at time zone 'Europe/Madrid';
  memory_count bigint;
  plan_count bigint;
  question_count bigint;
  selected_memories jsonb;
  selected_plans jsonb;
  curated_moments jsonb;
  fallback_moments jsonb;
  month_count integer;
  result jsonb;
begin
  select * into strict c from private.nuestro24_settings where singleton;

  if p_day is null or extract(day from p_day) <> 24 or p_day < c.first_event then
    raise exception 'Invalid edition date' using errcode = '22023';
  end if;

  month_count := (extract(year from p_day)::int - extract(year from c.relationship_date)::int) * 12
    + extract(month from p_day)::int - extract(month from c.relationship_date)::int;

  select count(*) into memory_count
  from public.recuerdos_app
  where nuestro24_fecha is null
    and fecha >= lower_day
    and fecha < p_day
    and created_at < upper_at;

  select count(*) into plan_count
  from public.propuestas
  where plan_date >= lower_day
    and plan_date <= p_day
    and status in ('confirmada','realizada');

  select count(*) into question_count
  from public.y_si_dias d
  where d.cerrada_at >= lower_at
    and d.cerrada_at < upper_at
    and exists (
      select 1 from public.y_si_respuestas r
      where r.dia_id = d.id and r.user_id = c.javi_id
    )
    and exists (
      select 1 from public.y_si_respuestas r
      where r.dia_id = d.id and r.user_id = c.laura_id
    );

  select coalesce(
    jsonb_agg(jsonb_build_object(
      'id', m.id,
      'title', m.titulo,
      'date', m.fecha,
      'description', m.descripcion,
      'photo_path', coalesce(m.image_paths[m.cover_index + 1], m.image_paths[1]),
      'type', m.tipo,
      'kind', 'memory'
    ) order by cardinality(m.image_paths) > 0 desc, m.fecha desc, m.id),
    '[]'::jsonb
  )
  into selected_memories
  from (
    select id, titulo, fecha, descripcion, image_paths, cover_index, tipo
    from public.recuerdos_app
    where nuestro24_fecha is null
      and fecha >= lower_day
      and fecha < p_day
      and created_at < upper_at
    order by cardinality(image_paths) > 0 desc, fecha desc, id
    limit 4
  ) m;

  select coalesce(
    jsonb_agg(jsonb_build_object(
      'id', p.id,
      'title', p.service_title,
      'date', p.plan_date,
      'time', p.plan_time,
      'description', p.note,
      'icon', p.service_icon,
      'status', p.status,
      'entry_type', p.entry_type,
      'kind', 'plan'
    ) order by p.plan_date desc, p.plan_time desc nulls last, p.id),
    '[]'::jsonb
  )
  into selected_plans
  from (
    select id, service_title, plan_date, plan_time, note, service_icon, status, entry_type
    from public.propuestas
    where plan_date >= lower_day
      and plan_date <= p_day
      and status in ('confirmada','realizada')
    order by plan_date desc, plan_time desc nulls last, created_at desc
    limit 4
  ) p;

  select coalesce(
    jsonb_agg(jsonb_build_object(
      'id', nm.id,
      'date', nm.moment_date,
      'kind', nm.kind,
      'visual', nm.visual_key,
      'eyebrow', nm.eyebrow,
      'title', nm.title,
      'description', nm.body,
      'source_type', nm.source_type,
      'source_id', nm.source_id,
      'photo_path', nm.photo_path
    ) order by nm.sort_order, nm.id),
    '[]'::jsonb
  )
  into curated_moments
  from private.nuestro24_moments nm
  where nm.edition_date = p_day;

  if jsonb_array_length(curated_moments) = 0 then
    select coalesce(jsonb_agg(item order by item->>'date'), '[]'::jsonb)
    into fallback_moments
    from (
      select item
      from jsonb_array_elements(selected_memories || selected_plans) as q(item)
      order by item->>'date' desc
      limit 6
    ) fallback;
  else
    fallback_moments := curated_moments;
  end if;

  result := jsonb_build_object(
    'schema', 'javieats-memory-v1',
    'kind', 'nuestro24',
    'version', 3,
    'actionLabel', 'Volver a nuestro mes',
    'event_date', p_day,
    'months', month_count,
    'period_start', lower_day,
    'period_end', p_day,
    'period_start_at', lower_at,
    'period_end_at', upper_at,
    'captured_at', now(),
    'hero_path', c.hero_path,
    'metrics', jsonb_build_array(
      jsonb_build_object('key','memories','value',memory_count,'label','Recuerdos guardados'),
      jsonb_build_object('key','plans','value',plan_count,'label','Planes confirmados'),
      jsonb_build_object('key','questions','value',question_count,'label','Preguntas entre los dos')
    ),
    'memories', selected_memories,
    'plans', selected_plans,
    'moments', fallback_moments,
    'letter_markdown', case when c.letter_month = p_day then c.letter_markdown else '' end
  );

  if char_length(result::text) > 30000 then
    raise exception 'Monthly snapshot exceeds the existing Memories limit';
  end if;

  return result;
end;
$$;

revoke all on function private.nuestro24_snapshot(date) from public, anon, authenticated;

create or replace function private.nuestro24_tick()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  c private.nuestro24_settings%rowtype;
  today date := (now() at time zone 'Europe/Madrid')::date;
  edition date;
  payload jsonb;
  paths text[];
  month_name text;
begin
  select * into c from private.nuestro24_settings where singleton for update;
  if not found or not c.enabled then return; end if;

  edition := make_date(extract(year from today)::int, extract(month from today)::int, 24);
  if today < edition or edition < c.first_event then return; end if;

  if not exists (select 1 from public.recuerdos_app where nuestro24_fecha = edition) then
    payload := private.nuestro24_snapshot(edition);

    select coalesce(array_agg(x.path order by x.rank), '{}'::text[])
    into paths
    from (
      select path, min(rank) as rank
      from (
        select c.hero_path as path, 0::bigint as rank
        union all
        select item->>'photo_path', 100 + ordinality
        from jsonb_array_elements(payload->'memories') with ordinality as s(item, ordinality)
        union all
        select item->>'photo_path', 200 + ordinality
        from jsonb_array_elements(payload->'moments') with ordinality as s(item, ordinality)
      ) candidates
      where path is not null and path <> ''
      group by path
    ) x;

    month_name := (array[
      'Enero','Febrero','Marzo','Abril','Mayo','Junio',
      'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'
    ])[extract(month from edition)::int];

    insert into public.recuerdos_app(
      created_by, fecha, titulo, descripcion, tipo, contenido,
      image_paths, cover_index, legacy_key, nuestro24_fecha
    )
    values(
      c.javi_id,
      edition,
      'Nuestro 24 · ' || month_name || ' ' || extract(year from edition)::int,
      (payload->>'months') || ' meses juntos',
      'letter',
      payload::text,
      paths,
      0,
      'nuestro24:' || to_char(edition,'YYYY-MM'),
      edition
    )
    on conflict (legacy_key) do nothing;
  end if;

  if c.notification_armed
    and c.notification_month = edition
    and c.notification_enqueued_at is null
    and today = edition
    and btrim(c.notification_title) <> ''
  then
    perform public.crear_notificacion(
      c.laura_id,
      c.javi_id,
      'nuestro24',
      c.notification_title,
      c.notification_body,
      'home',
      edition::text,
      'nuestro24:' || to_char(edition,'YYYY-MM') || ':laura'
    );
    update private.nuestro24_settings
    set notification_enqueued_at = now()
    where singleton;
  end if;
end;
$$;

revoke all on function private.nuestro24_tick() from public, anon, authenticated;
notify pgrst, 'reload schema';
